### ISSUE TITLE
I don't think u.s._minor_outlying_islands is a valid election entity

### ISSUE THREAD

**Issue by askpatrickw** [electioncal/us#19]
There are no permanently inhabited islands and they have no official governments. 
I was pretty sure of this because I used sail a lot and did some cruising, but  I did a little searching to verify:

https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands
>Except for Palmyra Atoll, all of these islands are unincorporated, unorganized territories of the United States. As of 2019, none of the islands have any permanent residents.

**Comment by tannewt** [comment]
Looks like I got it from here: https://github.com/electioncal/us/blob/main/geodata/state.txt (From the census.) Should we just remove it from the states structure so it doesn't get rendered in the drop down.

**Comment by askpatrickw** [comment]
Sounds good.  I'll send a PR for you.

**Comment by askpatrickw** [comment]
fixed and deployed
