### ISSUE TITLE
Set default state

### ISSUE THREAD

**Issue by reesericci** [electioncal/us#85]
In the code, is there any way to set a default state to show when viewing the homepage?

**Comment by tannewt** [comment]
There isn't. The homepage features the next upcoming reminder for all states.

What are you trying to do?

**Comment by reesericci** [comment]
Build a site that focuses on texas exclusively and has donations, voter registration links, etc. It will also only focus on the house, and only a couple districts.

**Comment by reesericci** [comment]
@tannewt any update?

**Comment by tannewt** [comment]
I was off outside today.

Why does that need to be a separate site? Could we just improve https://electioncal.us/en/texas/ ?

Alternatively, you could also integrate the reminder data into your own site via the csv or json feed. There are a lot of mechanics for feed creation and data maintenance I don't think you'll need.

**Comment by reesericci** [comment]
Fair enough. Will do
